version: "3.9"

services:
  frontend:
    build: .
    container_name: shitcrm_for_fullstack-frontend
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
